default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: localhost
  # pool: <%= ENV.fetch("DATABASE_POOL_SIZE") { 5 } %>
  # database: <%= ENV['DATABASE_NAME'] %>
  # port: <%= ENV['DATABASE_PORT'] %>

development:
  <<: *default
  database: jerb-board_development

test:
  <<: *default
  database: jerb-board_test

production:
  <<: *default
